In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn import metrics

In [2]:
def split_train_test(indep_X, dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
    return X_train, X_test, y_train, y_test

In [10]:
#Method for TfidfVectorizer
def HashingVectorizer(X_train, X_test):
    from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
    hash_Vectorizer = HashingVectorizer(n_features=2**16, stop_words='english', ngram_range=(1,2), alternate_sign=False)
    counter_Train = hash_Vectorizer.fit_transform(X_train)
    #counter_Train_dense = counter_Train.toarray()
    count_test = hash_Vectorizer.transform(X_test)
    #count_test_dense = count_test.toarray()
    #return counter_Train, count_test, hash_Vectorizer, counter_Train_dense, count_test_dense
    return counter_Train, count_test, hash_Vectorizer

In [4]:
#Method for MultinomialDB classification
def MultinomialNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import MultinomialNB
    clm = MultinomialNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [13]:
#Method for BernoulliNB classification
def BernoulliNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import BernoulliNB
    clm = BernoulliNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [14]:

#Method for ComplementNB classification
def ComplementNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import ComplementNB
    clm = ComplementNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [15]:
#Method for ComplementNB classification
def LogisticRegression_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.linear_model import LogisticRegression
    clm = LogisticRegression()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [16]:
#Method for ComplementNB classification
def LinearSVC_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.svm import LinearSVC
    clm = LinearSVC()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [5]:
def classification_report(y_test, pred):
    from sklearn.metrics import classification_report
    report=classification_report(y_test, pred)
    return report

In [6]:
#Print results
def print_results(score, cm, y_test, pred, modelName):
    print(f"Model Name:{modelName}")
    print("\naccuracy:   %0.3f" % score)
    print("\n")
    print("Confusion matrix \n ",cm)
    print("\n")
    print("Classification report \n ",report)

In [7]:
df = pd.read_csv('news.csv', index_col=None)
#print(df.head())
dataset=df.drop("Unnamed: 0", axis=1)
dep_Y=dataset["label"]
indep_X=dataset['text']
print(indep_X.head())

0    Daniel Greenfield, a Shillman Journalism Fello...
1    Google Pinterest Digg Linkedin Reddit Stumbleu...
2    U.S. Secretary of State John F. Kerry said Mon...
3    — Kaydee King (@KaydeeKing) November 9, 2016 T...
4    It's primary day in New York and front-runners...
Name: text, dtype: object


In [8]:
#Method calling for split training test set
X_train, X_test, y_train, y_test = split_train_test(indep_X, dep_Y)
print(y_test)

3789    REAL
733     FAKE
4783    FAKE
3067    FAKE
5288    REAL
        ... 
64      REAL
2306    REAL
3568    REAL
5717    FAKE
3353    FAKE
Name: label, Length: 1584, dtype: object


In [11]:
#counter_Train, count_test, hash_Vectorizer, counter_Train_dense, count_test_dense=HashingVectorizer(X_train, X_test)
counter_Train, count_test, hash_Vectorizer=HashingVectorizer(X_train, X_test)

In [12]:
score, cm, y_test, pred = MultinomialNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "MultinominalNB")

Model Name:MultinominalNB

accuracy:   0.863


Confusion matrix 
  [[588 179]
 [ 38 779]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.94      0.77      0.84       767
        REAL       0.81      0.95      0.88       817

    accuracy                           0.86      1584
   macro avg       0.88      0.86      0.86      1584
weighted avg       0.87      0.86      0.86      1584



In [17]:
score, cm, y_test, pred = BernoulliNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "BernoulliNB")

Model Name:BernoulliNB

accuracy:   0.740


Confusion matrix 
  [[633 134]
 [278 539]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.69      0.83      0.75       767
        REAL       0.80      0.66      0.72       817

    accuracy                           0.74      1584
   macro avg       0.75      0.74      0.74      1584
weighted avg       0.75      0.74      0.74      1584



In [18]:
score, cm, y_test, pred = ComplementNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "ComplementNB")

Model Name:ComplementNB

accuracy:   0.862


Confusion matrix 
  [[586 181]
 [ 37 780]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.94      0.76      0.84       767
        REAL       0.81      0.95      0.88       817

    accuracy                           0.86      1584
   macro avg       0.88      0.86      0.86      1584
weighted avg       0.87      0.86      0.86      1584



In [19]:
score, cm, y_test, pred = LogisticRegression_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "LogisticRegression")

Model Name:LogisticRegression

accuracy:   0.898


Confusion matrix 
  [[692  75]
 [ 86 731]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.89      0.90      0.90       767
        REAL       0.91      0.89      0.90       817

    accuracy                           0.90      1584
   macro avg       0.90      0.90      0.90      1584
weighted avg       0.90      0.90      0.90      1584



In [20]:
score, cm, y_test, pred = LinearSVC_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "LinearSVC")

Model Name:LinearSVC

accuracy:   0.926


Confusion matrix 
  [[708  59]
 [ 58 759]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.92      0.92      0.92       767
        REAL       0.93      0.93      0.93       817

    accuracy                           0.93      1584
   macro avg       0.93      0.93      0.93      1584
weighted avg       0.93      0.93      0.93      1584

