In [59]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn import metrics

In [60]:
def split_train_test(indep_X, dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
    return X_train, X_test, y_train, y_test

In [83]:
#Method for TfidfVectorizer
def TfidfVectorizer(X_train, X_test):
    from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
    tfidf_Vectorizer = TfidfVectorizer(stop_words='english')
    counter_Train = tfidf_Vectorizer.fit_transform(X_train)
    counter_Train_dense = counter_Train.toarray()
    #print(counter_Train)
    #print(X_test)
    count_test = tfidf_Vectorizer.transform(X_test)
    count_test_dense = count_test.toarray()
    #print(count_test)
    return counter_Train, count_test, tfidf_Vectorizer, counter_Train_dense, count_test_dense

In [62]:
#Method for Unique words count calculation
# Get the number of unique features (words) learned by CountVectorizer
# - count_vectorizer.get_feature_names_out(): returns an array of all words in the vocabulary
#   → This equals the number of features (columns) in your training matrix
def UniqueWordsCount(tfidf_Vectorizer):
    print(len(tfidf_Vectorizer.get_feature_names_out()))
    return(len(tfidf_Vectorizer.get_feature_names_out()))

In [63]:
#Method for MultinomialDB classification
def MultinomialNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import MultinomialNB
    clm = MultinomialNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [89]:
#Method for CategoricalNB classification
def CategoricalNB_cls(y_train, y_test, counter_Train_dense, count_test_dense):
    from sklearn.naive_bayes import CategoricalNB
    clm = CategoricalNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train_dense, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test_dense)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [79]:
#Method for BernoulliNB classification
def BernoulliNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import BernoulliNB
    clm = BernoulliNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [93]:

#Method for ComplementNB classification
def ComplementNB_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.naive_bayes import ComplementNB
    clm = ComplementNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [94]:
#Method for GaussianNB classification
def GaussianNB_cls(y_train, y_test, counter_Train_dense, count_test_dense):
    from sklearn.naive_bayes import GaussianNB
    clm = GaussianNB()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train_dense, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test_dense)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [97]:
#Method for ComplementNB classification
def LogisticRegression_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.linear_model import LogisticRegression
    clm = LogisticRegression()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [99]:
#Method for ComplementNB classification
def LinearSVC_cls(y_train, y_test, counter_Train, count_test):
    from sklearn.svm import LinearSVC
    clm = LinearSVC()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [101]:
#Method for CategoricalNB classification
def KNeighborsClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense):
    from sklearn.neighbors import KNeighborsClassifier
    clm = KNeighborsClassifier()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train_dense, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test_dense)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [102]:
#Method for CategoricalNB classification
def DecisionTreeClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense):
    from sklearn.tree import DecisionTreeClassifier
    clm = DecisionTreeClassifier()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train_dense, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test_dense)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [103]:

#Method for CategoricalNB classification
def RandomForestClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense):
    from sklearn.ensemble import RandomForestClassifier
    clm = RandomForestClassifier()

# Step 2: Train (fit) the classifier on the training data
# - count_train: the bag-of-words matrix for training documents
# - y_train: the true labels (e.g., FAKE or REAL) for training data
    clm.fit(counter_Train_dense, y_train)

# Step 3: Predict labels for the test data
# - count_test: the bag-of-words matrix for test documents
# - pred: the predicted labels for each test document
    pred = clm.predict(count_test_dense)

# Step 4: Calculate accuracy score
# - Compares predicted labels (pred) with true labels (y_test)
# - Returns the proportion of correct predictions
    score = metrics.accuracy_score(y_test, pred)

# Step 5: Print accuracy with 3 decimal places
    #print("accuracy:   %0.3f" % score)

# Step 6: Generate confusion matrix
# - Compares true labels (y_test) with predicted labels (pred)
# - labels=['FAKE','REAL']: ensures matrix rows/columns are ordered
#   consistently for FAKE and REAL classes
    cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
    return score, cm, y_test, pred

In [64]:
def classification_report(y_test, pred):
    from sklearn.metrics import classification_report
    report=classification_report(y_test, pred)
    return report

In [74]:
#Print results
def print_results(score, cm, y_test, pred, modelName):
    print(f"Model Name:{modelName}")
    print("\naccuracy:   %0.3f" % score)
    print("\n")
    print("Confusion matrix \n ",cm)
    print("\n")
    print("Classification report \n ",report)

In [67]:
df = pd.read_csv('news.csv', index_col=None)
#print(df.head())
dataset=df.drop("Unnamed: 0", axis=1)
dep_Y=dataset["label"]
indep_X=dataset['text']
print(indep_X.head())

0    Daniel Greenfield, a Shillman Journalism Fello...
1    Google Pinterest Digg Linkedin Reddit Stumbleu...
2    U.S. Secretary of State John F. Kerry said Mon...
3    — Kaydee King (@KaydeeKing) November 9, 2016 T...
4    It's primary day in New York and front-runners...
Name: text, dtype: object


In [68]:
#Method calling for split training test set
X_train, X_test, y_train, y_test = split_train_test(indep_X, dep_Y)
print(y_test)

3789    REAL
733     FAKE
4783    FAKE
3067    FAKE
5288    REAL
        ... 
64      REAL
2306    REAL
3568    REAL
5717    FAKE
3353    FAKE
Name: label, Length: 1584, dtype: object


In [85]:
counter_Train, count_test, tfidf_Vectorizer, counter_Train_dense, count_test_dense=TfidfVectorizer(X_train, X_test)

In [86]:
uniqueWords=UniqueWordsCount(tfidf_Vectorizer)
print(uniqueWords)

59647
59647


In [87]:
score, cm, y_test, pred = MultinomialNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "MultinominalNB")

Model Name:MultinominalNB

accuracy:   0.836


Confusion matrix 
  [[530 237]
 [ 22 795]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.96      0.69      0.80       767
        REAL       0.77      0.97      0.86       817

    accuracy                           0.84      1584
   macro avg       0.87      0.83      0.83      1584
weighted avg       0.86      0.84      0.83      1584



In [90]:
score, cm, y_test, pred = CategoricalNB_cls(y_train, y_test, counter_Train_dense, count_test_dense)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "CategoricalNB")

Model Name:CategoricalNB

accuracy:   0.484


Confusion matrix 
  [[767   0]
 [817   0]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.48      1.00      0.65       767
        REAL       0.00      0.00      0.00       817

    accuracy                           0.48      1584
   macro avg       0.24      0.50      0.33      1584
weighted avg       0.23      0.48      0.32      1584



C:\Users\DELL\anaconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\DELL\anaconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\DELL\anaconda3\envs\ml_ai\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [91]:
score, cm, y_test, pred = BernoulliNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "BernoulliNB")

Model Name:BernoulliNB

accuracy:   0.823


Confusion matrix 
  [[687  80]
 [201 616]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.77      0.90      0.83       767
        REAL       0.89      0.75      0.81       817

    accuracy                           0.82      1584
   macro avg       0.83      0.82      0.82      1584
weighted avg       0.83      0.82      0.82      1584



In [95]:
score, cm, y_test, pred = GaussianNB_cls(y_train, y_test, counter_Train_dense, count_test_dense)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "GaussianNB")

Model Name:GaussianNB

accuracy:   0.822


Confusion matrix 
  [[608 159]
 [123 694]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.83      0.79      0.81       767
        REAL       0.81      0.85      0.83       817

    accuracy                           0.82      1584
   macro avg       0.82      0.82      0.82      1584
weighted avg       0.82      0.82      0.82      1584



In [96]:
score, cm, y_test, pred = ComplementNB_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "ComplementNB")

Model Name:ComplementNB

accuracy:   0.835


Confusion matrix 
  [[526 241]
 [ 20 797]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.96      0.69      0.80       767
        REAL       0.77      0.98      0.86       817

    accuracy                           0.84      1584
   macro avg       0.87      0.83      0.83      1584
weighted avg       0.86      0.84      0.83      1584



In [98]:
score, cm, y_test, pred = LogisticRegression_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "LogisticRegression")

Model Name:LogisticRegression

accuracy:   0.914


Confusion matrix 
  [[714  53]
 [ 83 734]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.90      0.93      0.91       767
        REAL       0.93      0.90      0.92       817

    accuracy                           0.91      1584
   macro avg       0.91      0.91      0.91      1584
weighted avg       0.91      0.91      0.91      1584



In [100]:
score, cm, y_test, pred = LinearSVC_cls(y_train, y_test, counter_Train, count_test)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "LinearSVC")

Model Name:LinearSVC

accuracy:   0.931


Confusion matrix 
  [[714  53]
 [ 56 761]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.93      0.93      0.93       767
        REAL       0.93      0.93      0.93       817

    accuracy                           0.93      1584
   macro avg       0.93      0.93      0.93      1584
weighted avg       0.93      0.93      0.93      1584



In [104]:
score, cm, y_test, pred = KNeighborsClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "KNeighborsClassifie")

Model Name:KNeighborsClassifie

accuracy:   0.549


Confusion matrix 
  [[767   0]
 [714 103]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.52      1.00      0.68       767
        REAL       1.00      0.13      0.22       817

    accuracy                           0.55      1584
   macro avg       0.76      0.56      0.45      1584
weighted avg       0.77      0.55      0.45      1584



In [105]:
score, cm, y_test, pred = DecisionTreeClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "DecisionTreeClassifier")

Model Name:DecisionTreeClassifier

accuracy:   0.808


Confusion matrix 
  [[612 155]
 [149 668]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.80      0.80      0.80       767
        REAL       0.81      0.82      0.81       817

    accuracy                           0.81      1584
   macro avg       0.81      0.81      0.81      1584
weighted avg       0.81      0.81      0.81      1584



In [106]:
score, cm, y_test, pred = RandomForestClassifier_cls(y_train, y_test, counter_Train_dense, count_test_dense)
report = classification_report(y_test, pred)
#print("accuracy:   %0.3f" % score)
#print(cm)
print_results(score, cm, y_test, pred, "RandomForestClassifier")

Model Name:RandomForestClassifier

accuracy:   0.907


Confusion matrix 
  [[691  76]
 [ 72 745]]


Classification report 
                precision    recall  f1-score   support

        FAKE       0.91      0.90      0.90       767
        REAL       0.91      0.91      0.91       817

    accuracy                           0.91      1584
   macro avg       0.91      0.91      0.91      1584
weighted avg       0.91      0.91      0.91      1584

